version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
  app-notas:
    container_name: app-notas
    restart: always
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    
    
  
