name: Deployement

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      dbhost: ${{secrets.MONGO_DB_HOST}}
      dbport: ${{secrets.MONGO_DB_PORT}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18  
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
            mongodb-version: 6.0
            mongodb-port: ${{ secrets.MONGO_DB_PORT }}
      - name: Imprimir secretos
        run: |
            echo "$MONGO_DB_HOST"
      - name: Install dependecies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: build
        run: npm run start
      - name: tests
        run: npm run test